---
- name: Deploy Zabbix sever
  hosts: zabbix-server
  remote_user: centos
  become: yes
  pre_tasks:
    - name: Update SELinux Booleans
      seboolean:
        name: "{{ item.name }}"
        persistent: yes
        state: "{{ item.state }}"
      with_items:
        - { name: "httpd_can_network_connect_db", state: yes }
        - { name: "daemons_enable_cluster_mode", state: yes }
  roles:
    - role: geerlingguy.apache
    - role: dj-wasabi.zabbix-server
    - role: dj-wasabi.zabbix-web
    #- selinux-module
